'use client';

import { useState, useRef } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Upload, Loader2, FileJson } from 'lucide-react';
import { toast } from 'sonner';
import { importUserDataJSON } from '@/actions/import';
import { useRouter } from 'next/navigation';

export function DataImport() {
    const [isLoading, setIsLoading] = useState(false);
    const [file, setFile] = useState<File | null>(null);
    const router = useRouter();
    const fileInputRef = useRef<HTMLInputElement>(null);

    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files[0]) {
            setFile(e.target.files[0]);
        }
    };

    const handleImport = async () => {
        if (!file) return;

        setIsLoading(true);
        const reader = new FileReader();

        reader.onload = async (e) => {
            const content = e.target?.result as string;
            if (!content) {
                toast.error('Failed to read file');
                setIsLoading(false);
                return;
            }

            try {
                const result = await importUserDataJSON(content);
                if (result.success) {
                    toast.success('Data imported successfully');
                    setFile(null);
                    if (fileInputRef.current) fileInputRef.current.value = '';
                    router.refresh();
                }
            } catch (error) {
                console.error(error);
                toast.error('Failed to import data. Please check the file format.');
            } finally {
                setIsLoading(false);
            }
        };

        reader.readAsText(file);
    };

    return (
        <Card>
            <CardHeader>
                <CardTitle className="flex items-center gap-2">
                    <Upload className="h-5 w-5" />
                    Import Data
                </CardTitle>
                <CardDescription>
                    Restore your data from a JSON backup file. This will add to your existing data.
                </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
                <div className="flex flex-col gap-4">
                    <input
                        ref={fileInputRef}
                        type="file"
                        accept="application/json"
                        onChange={handleFileChange}
                        className="hidden"
                    />

                    <div className="flex flex-col sm:flex-row items-start sm:items-center gap-4">
                        <Button
                            variant="outline"
                            onClick={() => fileInputRef.current?.click()}
                            disabled={isLoading}
                        >
                            <FileJson className="mr-2 h-4 w-4" />
                            {file ? 'Change File' : 'Select Backup File'}
                        </Button>

                        {file && (
                            <div className="flex items-center gap-4">
                                <span className="text-sm font-medium truncate max-w-[200px]">
                                    {file.name}
                                </span>
                                <Button
                                    onClick={handleImport}
                                    disabled={isLoading}
                                >
                                    {isLoading ? (
                                        <>
                                            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                                            Importing...
                                        </>
                                    ) : (
                                        <>
                                            <Upload className="mr-2 h-4 w-4" />
                                            Start Import
                                        </>
                                    )}
                                </Button>
                            </div>
                        )}
                    </div>

                    <p className="text-xs text-muted-foreground">
                        * Only supports .json files generated by the Export feature.
                        <br />
                        * Imported data will be added as new entries. Duplicates may occur if importing the same file twice.
                    </p>
                </div>
            </CardContent>
        </Card>
    );
}
